:project: mastodonpp
:uri-base: https://schlomp.space/tastytea/{project}
:uri-coc: {uri-base}/src/branch/main/CODE_OF_CONDUCT.adoc
:contact-email: tastytea@tastytea.de
:contact-xmpp: {contact-email}
:contact-fediverse: https://likeable.space/users/tastytea
:uri-git-format-patch: https://git-scm.com/docs/git-format-patch
:uri-git-send-email: https://git-scm.com/docs/git-send-email

== How to contribute

Read the link:{uri-coc}[Code of Conduct].

=== Reporting bugs or suggesting enhancements

Before reporting a bug, please
https://schlomp.space/tastytea/{project}/issues[perform a search] to see if the
problem has already been reported. If it has, add a comment to the existing
issue instead of opening a new one. Same for enhancements.

You can also contact me via mailto:{contact-email}[E-Mail],
link:xmpp:{contact-xmpp}[XMPP] or the {contact-fediverse}[Fediverse] if you
don't want to open an account.

=== Pull requests

Please use similar coding conventions as the rest of the project. The basic rule
to remember is to write code in the same style as the existing/surrounding
code. Add a copyright line with the year, your name and your email address to
the files you edited, unless you don't want to.

You can also send me your patches via mailto:{contact-email}[E-Mail], ideally
using link:{uri-git-format-patch}[git format-patch] or
link:{uri-git-send-email}[git send-email].
